---
title: "Publications"
output: distill::distill_article
---

1.  Williams, W.C., Leong, Y.C., Collier, E.A., Nook, E.C., **Son, J.**, & Zaki, J. (in prep). Communicating emotion through facial expressions: Social consequences and neural correlates.

1.  **Son, J.**, Bhandari, A., & FeldmanHall, O. (revise & resubmit). Cognitive maps of social features enable adaptive inference in social networks.

1.  Heffner, J., **Son, J.**, & FeldmanHall, O. (revise & resubmit). Emotion prediction errors guide socially adaptive behavior.

1.  **Son, J.**, Bhandari, A., & FeldmanHall, O. (2019). Crowdsourcing punishment: Individuals reference group preferences to inform their own punitive decisions. *Scientific Reports.* [**Online (Open Access)**](https://www.nature.com/articles/s41598-019-48050-2) \| [**PDF**](https://jaeyoungson.com/papers/CrowdsourcingPunishment_SciRep_2019.pdf) \| [**Data & Code**](https://osf.io/8ka47/)

1.  FeldmanHall, O., **Son, J.**, & Heffner, J. (2018). Norms and the flexibility of moral action. *Personality Neuroscience.* [**Online (Open Access)**](https://www.cambridge.org/core/journals/personality-neuroscience/article/norms-and-the-flexibility-of-moral-action/A8A5140A517ECEE314A21FF9FE0E9EED) \| [**PDF**](https://jaeyoungson.com/papers/NormsMoralAction_PN_2018.pdf)

*Disclaimer: The PDFs provided may be copyrighted by the journals/edited volumes in which they are published. Access to these articles is provided to facilitate timely distribution of scientific knowledge, and is therefore intended for your personal use only. No commercial use may be made of these articles, nor is mass production of these articles permitted.*
