---
title: "Publications"
---

An index of my publications can also be found on [**Google Scholar**](https://scholar.google.com/citations?user=JPPuzI8AAAAJ).

## Published work

**Early insight into social network structure predicts climbing the social ladder.**\
Aslarus, I.C., **Son, J.**, Xia, A., & FeldmanHall, O. (2025). *Science Advances.*\
[Online](https://www.science.org/doi/10.1126/sciadv.ads2133) \| [PDF](/files/papers/2025_SciAdv_SocialLadder.pdf) \| [Data](https://datadryad.org/dataset/doi:10.5061/dryad.2280gb63t) \| [Code](https://zenodo.org/records/14792211)

**Abstract cognitive maps for complex social systems.**\
FeldmanHall, O., **Son, J.**, & Bhandari, A. (2025). *Current Directions in Psychological Science.*\
[Online](https://journals.sagepub.com/doi/10.1177/09637214251342742) \| [PDF](/files/papers/2025_CDP_AbstractCogMaps.pdf)

**Replay shapes abstract cognitive maps for efficient social navigation.**\
**Son, J.**\*, Vives, M-L.\*, Bhandari, A., & FeldmanHall, O. (2024). *Nature Human Behaviour.*\
\* *Equal contribution.*\
[Online](https://www.nature.com/articles/s41562-024-01990-w) \| [PDF](/files/papers/2024_NHB_NavigationReplay.pdf) \| [Data & Code](https://github.com/feldmanhalllab/network-navigation-replay)

**Abstract cognitive maps of social network structure aid adaptive inference.**\
**Son, J.**, Bhandari, A., & FeldmanHall, O. (2023). *Proceedings of the National Academy of Sciences.*\
[Online](https://www.pnas.org/doi/10.1073/pnas.2310801120) \| [PDF](/files/papers/2023_PNAS_MultistepAbstraction.pdf) \| [Data & Code](https://github.com/feldmanhalllab/multistep-relational-abstraction)

**Cognitive maps of social features enable flexible inference in social networks.**\
**Son, J.**, Bhandari, A., & FeldmanHall, O. (2021). *Proceedings of the National Academy of Sciences.*\
[Online](https://www.pnas.org/doi/10.1073/pnas.2021699118) \| [PDF](/files/papers/2021_PNAS_SocialFeatures.pdf) \| [Data & Code](https://osf.io/v8ucz/)

**Emotion prediction errors guide socially adaptive behaviour.**\
Heffner, J., **Son, J.**, & FeldmanHall, O. (2021). *Nature Human Behaviour.*\
[Online](https://www.nature.com/articles/s41562-021-01213-6) \| [PDF](/files/papers/2021_NHB_EPE.pdf) \| [Data & Code](https://github.com/jpheffne/epe)

**Crowdsourcing punishment: Individuals reference group preferences to inform their own punitive decisions.**\
**Son, J.**, Bhandari, A., & FeldmanHall, O. (2019). *Scientific Reports.*\
[Online](https://www.nature.com/articles/s41598-019-48050-2) \| [PDF](/files/papers/2019_SciRep_CrowdsourcingPunishment.pdf) \| [Data & Code](https://osf.io/8ka47/)

**Norms and the flexibility of moral action.**\
FeldmanHall, O., **Son, J.**, & Heffner, J. (2018). *Personality Neuroscience.*\
[Online](https://www.cambridge.org/core/journals/personality-neuroscience/article/norms-and-the-flexibility-of-moral-action/A8A5140A517ECEE314A21FF9FE0E9EED) \| [PDF](/files/papers/2018_PN_NormsMoralAction.pdf)

## Unpublished work

**Medial temporal lobe encodes cognitive maps of real-world social networks.**\
Teoh, Y.Y.\*, **Son, J.**\*, Xia, A., Bhandari, A., & FeldmanHall, O. (preprint). *bioRxiv.*\
\* *Equal contribution.*\
[Online (preprint)](https://www.biorxiv.org/content/10.1101/2025.03.18.643925v1)

**Communicating emotion through facial expressions: Social consequences and neural correlates.**\
Williams, W.C., Leong, Y.C., Collier, E.A., Nook, E.C., **Son, J.**, & Zaki, J. (preprint). *PsyArXiv.*\
[Online (preprint)](https://psyarxiv.com/4zpfk/)

::: {style="font-size: 80%; font-style: italic"}
Disclaimer: The PDFs provided may be copyrighted by the journals/edited volumes in which they are published. Access to these articles is provided to facilitate timely distribution of scientific knowledge, and is therefore intended for your personal use only. No commercial use may be made of these articles, nor is mass production of these articles permitted.
:::
