---
title: "CV & Publications"
output:
  distill::distill_article:
    toc: true
    toc_depth: 1
    toc_float: true
---

[**Full CV (PDF)**](https://jaeyoungson.com/cv.pdf) \| [**Google Scholar**](https://scholar.google.com/citations?user=JPPuzI8AAAAJ)

# Publications

1.  Heffner, J., **Son, J.**, & FeldmanHall, O. (2021). Emotion prediction errors guide socially adaptive behaviour. *Nature Human Behaviour.*\
    [**Online**](https://www.nature.com/articles/s41562-021-01213-6) **\| [PDF](https://jaeyoungson.com/papers/EPE_NHB_2021.pdf) \| [Data & Code](https://github.com/jpheffne/epe)**

2.  **Son, J.**, Bhandari, A., & FeldmanHall, O. (2021). Cognitive maps of social features enable flexible inference in social networks. *Proceedings of the National Academy of Sciences*.\
    [**Online**](https://www.pnas.org/content/118/39/e2021699118) **\| [PDF](https://jaeyoungson.com/papers/CogMaps_PNAS_2021.pdf) \| [Data & Code](https://osf.io/v8ucz/)**

3.  **Son, J.**, Bhandari, A., & FeldmanHall, O. (2019). Crowdsourcing punishment: Individuals reference group preferences to inform their own punitive decisions. *Scientific Reports.*\
    [**Online (Open Access)**](https://www.nature.com/articles/s41598-019-48050-2) **\| [PDF](https://jaeyoungson.com/papers/CrowdsourcingPunishment_SciRep_2019.pdf) \| [Data & Code](https://osf.io/8ka47/)**

4.  FeldmanHall, O., **Son, J.**, & Heffner, J. (2018). Norms and the flexibility of moral action. *Personality Neuroscience.*\
    [**Online (Open Access)**](https://www.cambridge.org/core/journals/personality-neuroscience/article/norms-and-the-flexibility-of-moral-action/A8A5140A517ECEE314A21FF9FE0E9EED) **\| [PDF](https://jaeyoungson.com/papers/NormsMoralAction_PN_2018.pdf)**

# Unpublished Work

4.  Williams, W.C., Leong, Y.C., Collier, E.A., Nook, E.C., **Son, J.**, & Zaki, J. (preprint). Communicating emotion through facial expressions: Social consequences and neural correlates. *PsyArXiv.*\
    [**Online (preprint)**](https://psyarxiv.com/4zpfk/)

5.  **Son, J.** (in prep). Abstraction underlies learning of social network structure.

```{r echo=FALSE}
htmltools::p(
  "
  Disclaimer: The PDFs provided may be copyrighted by the journals/edited volumes
  in which they are published. Access to these articles is provided to facilitate
  timely distribution of scientific knowledge, and is therefore intended for your
  personal use only. No commercial use may be made of these articles, nor is mass
  production of these articles permitted.
  ",
  style = "font-size: 70%; font-style: italic"
)
```

# Experience

-   **Ph.D.** (2018 - expected 2023)

    -   Brown University, Dept. of Cognitive, Linguistic, & Psychological Sciences (CLPS)
    -   Supervisor: Oriel FeldmanHall

-   **Lab Manager** (2016-2018)

    -   Brown University, Dept. of Cognitive, Linguistic, & Psychological Sciences (CLPS)
    -   Supervisor: Oriel FeldmanHall

-   **Research Assistant** (2013-2016)

    -   Stanford University, Dept. of Psychology
    -   Supervisors: Jamil Zaki & W. Craig Williams

-   **B.A.** (2012-2016)

    -   Stanford University

# Grants & Fellowships

-   National Science Foundation Graduate Research Fellowship Program (2019-2022)

-   Brown University Graduate Travel Grant (2019)

-   Stanford Undergraduate Advising & Research "Small Grant" (2015)

-   Stanford Undergraduate Teaching Fellowship (2014)

-   Stanford PsychSummer Grant (2013)
