---
title: "Thoughts as I begin the grad school application process"
date: September 16, 2017
output:
  distill::distill_article:
    toc: true
    toc_float: true
    self_contained: false
categories:
  - grad school
---

This blog post was originally written on September 16, 2017. It was last updated on `r Sys.Date()` using R Markdown.

As much as I would like to continue to ignore that it's mid-September, I can no longer maintain the illusion that I've got a great deal of time left before grad school and grant applications are due. When it comes to thinking about my future, I am planful to a fault, and though I have learned to be less rigid in my thinking, it is not my automatic response to be relaxed about impending risky decisions. Tomes have been written about impostor syndrome and social comparison and anxiety and every other thing that afflicts academics, but writing posts like this help me reaffirm my values. Here are some thoughts I'm having as I (properly!) begin the grad school application process, mostly in the form of platitudes:

1.  **Everyone you admire was once where you are now.** They've felt (and even among the prestigious scientists I know, continue to feel) unsure of themselves. They've made mistakes, and maybe even catastrophic ones. They've questioned their direction, or aptitude, or competence. They've experienced failure and disappointment and frustration and regret. They've lost perspective and have cried over silly things, which later turned out to be relatively inconsequential. What's the difference between you and those scientists you admire? Many, many years of relentless training and learning and building up resilience.

2.  **There isn't one right way to take care of yourself.** It used to drive me crazy when people tell me to practice self-care because I had no idea what that meant. It does not make me feel good to sit around and do nothing. The notion that I take a bubble bath, drink wine, and watch Netflix to unwind is actually stress-inducing to me; I need to funnel my energy into some form of work that I find meaningful. Sometimes, that means wrapping up work-related loose ends so that I can free up my mind to think about more important things. Other times, it means doing chores that are mindless but necessary: vacuuming, doing laundry, running errands, meal prep, etc. As a proper demonstration of how nerdy I am, sometimes self-care looks like reading newly-published articles and getting inspired about follow-ups I might want to conduct, which I find invigorating. People who aren't incorrigible nerds look at me and worry that I'm a workaholic. Though I appreciate their concern and understand why they might believe that, I've found a balance that works for me, at least for now. The point isn't that you engage in rituals or follow other people's rules about self-care. The whole point is that you find some way of taking care of yourself, and only you know what that looks like.

3.  **On the other hand, there are many wrong ways to take care of yourself.** It's one thing to go out to the bar with friends at the end of a long week; it's quite another to use alcohol to manage stress on a daily basis. There's a difference between managing and coping. If you ever hear a nagging voice in the back of your head, or if friends tell you that they're concerned for you, take that as a serious sign to stop and self-evaluate. If you need help, there's nothing shameful or burdensome about asking for help.

4.  In fact, that last thing I wrote is important enough to bear repeating: **if you need help, there's nothing shameful or burdensome about asking for help.** If you knew that your friend was feeling what you're feeling now, would you want them to keep it to themselves?

5.  **It is exhausting pretending to be someone who isn't you, and people can usually see through it anyways.** People generally like authenticity. If you're hanging around people who don't appreciate you for being you, maybe you need to find different people to hang out with.

6.  **Listen to your emotions.** Oftentimes, when I'm stressed out, it's not being fueled by 'stress' *per se*. Instead, for me, 'stress' is a cognitive label I apply to the emotional experience of feeling fearful: afraid of the consequences of not meeting a deadline, or of disappointing someone, or of uncertainty looming on the horizon. At any rate, your emotions are usually trying to cue you into the fact that you might not be doing too great.

7.  **Figure out what your fears are and confront them head-on.** This works for me, anyways. I was once stressed out about an analysis I was performing. I realized that the reason I was stressed out was because I was afraid that: 1) my inability to perform the analysis meant that I was an idiot; 2) I was doing the entire analysis wrong, and didn't even know enough about what I was doing to figure out why it might be wrong; 3) in the worst-case scenario, nobody else would catch any mistakes I made, and then we'd have to retract a paper once a reader figured out that the analyses were done incorrectly, and then I would besmirch the reputations of my collaborators and advisors. I immediately stopped working on the analysis and started to read up on the underlying theory of the analysis I was performing. Though it took me a few days to gain a sense of familiarity with the theory, having a little bit of statistical knowledge both put my mind at ease and made me a smarter scientist. I am firmly of the opinion that no good can come of ignoring things you're afraid of.

8.  **Making mistakes means that you're learning; failure means you're trying.** I get caught up on this a lot. I don't like making mistakes, and I absolutely hate feeling like a failure. But there is nothing bad about learning or trying, and it is impossible to do either without making mistakes and failing. This is something I would do well to remind myself more often.

9.  **You don't make plans to follow through with them; you make plans to think about your values, direction, and aspirations.** Very little of my life goes according to plan, which is a good thing. My life would be utterly tepid if my harebrained schemes actually worked. I sometimes make the mistake of thinking that the plans I devise are intrinsically valuable, and that the point of making plans is to follow them. Rather, I think making plans forces you to decide (at least internally) what your values are, which determines the direction you take (but importantly, not the path!), and this tells you something about your hopes and aspirations. So when you're faced with reality, and your carefully-constructed plans fall to bits, you still have a foundation to stand on: you know who you are, what you want, and where you want to go.

10. **You are constantly creating yourself.** Every choice either brings you closer to (or pushes you further away from) the person you want to be. In the grand scheme of all things that exist, there's very little that we can bring under our direct control. If I'm on a sailboat, there's not much I can do if there's no wind. However, in the meantime, I can put up my sails and prepare for incoming gusts. This is how I think about choices: you can't control your life, but you can push the odds in your favor. In the process of doing this, you're incrementally crafting yourself into the person you want to be.
