---
title: "PsychBlog & Jelly"
date: August 16, 2017
output:
  distill::distill_article:
    toc: true
    toc_float: true
    self_contained: false
categories:
  - meta
---

This blog post was originally written on August 16, 2017. It was last updated on `r Sys.Date()` using R Markdown.

# What is PsychBlog & Jelly?

Einstein famously quipped that nobody understands anything until they can explain it to their grandmother. Given that my Korean language skills are dreadful on a good day, I suppose that I'm doomed to a life of not understanding anything past, "I'm hungry."

Yet, in spite of myself, I've managed to learn a few things here and there about psychology, research, and life as an academic. My hope is to share some of the things I've learned, on the off chance that someone else finds it helpful.

# What can I expect to see on PsychBlog & Jelly?

Honestly, I'm not sure either, but I hope it'll be interesting.

# *Why* PsychBlog & Jelly?

1. I'm incorrigible when it comes to dumb backronyms.
2. Peanut butter and jelly sandwiches are simple but satisfying. They don't pretend to be anything special, but they're a great go-to when you need a quick fix.
3. I feel like I was trying to sketch the outlines for some quasi-deep metaphor, but now I'm just hungry.